### ISSUE TITLE
Train&Training evaluate

### ISSUE THREAD

**Issue by Vio1etovo** [pjl1995/CTracker#18]
I found that num_workers=32 and default epochs=100 in DataLoder during training. Are these all necessary?  Using these default settings, there are many problems in training, such as out of memory, [Errno111] and so on.  I reduced these two parameters, and it looks normal at the moment.  
In addition, are there any training evaluation function in the code?

**Comment by pjl1995** [comment]
1. It is not necessary and you can reduce it.
2. In training you can get the .txt files, you can evaluate it by the devkit in MOT challenge:
https://github.com/dendorferpatrick/MOTChallengeEvalKit

**Comment by fadilkamal** [comment]
You can also create a code for evaluation using motmetrics using the .txt generated:
https://github.com/cheind/py-motmetrics
