### ISSUE TITLE
About CSV file

### ISSUE THREAD

**Issue by KevinKai-0717** [pjl1995/CTracker#19]
First of all, thank you very much for your open source work！I want to know how to generate CSV files for other datasets other than MOT17?

**Comment by pjl1995** [comment]
You can convert the data format of other datasets into CTracker's CSV format.

**Comment by KevinKai-0717** [comment]
> You can convert the data format of other datasets into CTracker's CSV format.
Thank you for your reply! Can you provide the code to convert the MOTChallenge dataset format into a CSV file?

**Comment by pjl1995** [comment]
Sorry that I have not organize it, because this script is not complex and the conversion of different databases is different.

**Comment by KevinKai-0717** [comment]
thank you for your reply! I would like to ask whether the model is directly loaded with ResNet50 weights and trained on the MOT17 training set？

**Comment by pjl1995** [comment]
Yes
