### ISSUE TITLE
How to measure FPS (Hz) in your network?

### ISSUE THREAD

**Issue by black12357** [pjl1995/CTracker#27]
Thank you for your great work? Did you have one example for measuring FPS in your network?
Thank you so much! I'm looking forward to from you.

**Comment by pjl1995** [comment]
It is easy to achieve. You can set a time point before and after each module. Then you can calculate the fps based on the sum of the accumulated time and the number of the frames.

**Comment by black12357** [comment]
Thank you for your reply! I will try to compute FPS based on your comments.
