### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.nms'

### ISSUE THREAD

**Issue by jinyl777** [pjl1995/CTracker#5]
I follow your read me but sh lib/build.sh not work and I got  ModuleNotFoundError: No module named 'lib.nms'

**Comment by pjl1995** [comment]
What is the log output after you run the command sh lib/build.sh ?

**Comment by jinyl777** [comment]
The output is :
g++ -pthread -shared -L/home/guow/anaconda3/envs/CTtrack/lib -Wl,-rpath=/home/guow/anaconda3/envs/CTtrack/lib,--no-as-needed -L/home/guow/anaconda3/envs/CTtrac/lib -Wl,-rpath=/home/guow/anaconda3/envs/CTtrack/lib,--no-as-needed build/temp.linux-x86_64-3.6/nms_kernel.o build/temp.linux-x86_64-3.6/gpu_nms.o -L/usr/loca/cuda/lib64 -L/home/guow/anaconda3/envs/CTtrack/lib -Wl,--enable-new-dtags,-R/usr/local/cuda/lib64 -lcudart -lpython3.6m -o /home/guow/jin/CTracker-master/lib/ython_nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so

**Comment by chenrxi** [comment]
I also got ModuleNotFoundError: No module named 'lib.nms'

**Comment by chenrxi** [comment]
Oh, you can copy the nms.py from the dir **simpledet/operator_py** @jinyl777

**Comment by pjl1995** [comment]
What is your pytorch version？
@jinyl777

**Comment by jinyl777** [comment]
pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    @pjl1995

**Comment by jinyl777** [comment]
I will try it and thankyou very much @chenrxi

**Comment by jinyl777** [comment]
I copy the  simpledet/operator_py/nms.py to lib and modify the line2 .cython.cpu_nms to .cpython_nms .
Then  I got   No module named 'run_for_track' , well seach the file but do not get the file 
Is I miss some file ?

**Comment by jinyl777** [comment]
I copy the simpledet/operator_py/nms.py to lib and modify the line2 .cython.cpu_nms to .cpython_nms .
Then I got No module named 'run_for_track' , well seach the file but do not get the file
Is I miss some file ? @pjl1995

**Comment by pjl1995** [comment]
I am sorry that I forget to modify it. You can just modify 'run_for_track' to 'test' in train.py and it's OK.
@jinyl777

**Comment by jinyl777** [comment]
I modify it and it can run, thanks I will close the issue

**Comment by jinyl777** [comment]
I modify it and it can run, thanks I will close the issue @pjl1995

**Comment by pjl1995** [comment]
Hi all, I am so sorry that I forgot to add the nms.py in the lib folder. Now this bug is fixed and you can download the latest code.
